version: '3.7'

services:
  db:
    container_name: ${SQL_HOST}
    image: postgres
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DB}
      - POSTGRES_PORT=${SQL_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - ${SQL_PORT}
    restart: always


  web:
    container_name: ${BACKEND_NAME}
    build: ./signalmanager
    env_file:
      - ./.env
    expose:
      - ${WEB_HTTP_INTERNAL}
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - ${WEB_HTTP_PORT}:80
      - ${WEB_HTTPS_PORT}:443
    depends_on:
      - web
    env_file:
      - ./.env

volumes:
  postgres_data:
    name: ${POSTGRES_VOLUME}

networks:
  default:
    name: signal_manager_network
    driver: bridge
