version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
      - ${WEB_HTTP_PORT}:80
      - ${WEB_HTTPS_PORT}:443
    volumes:
       - ${CERT_FILE}:/etc/ssl/certs/cert.crt
       - ${KEY_FILE}:/etc/ssl/private/cert.key
    env_file:
      - ./.env

networks:
  default:
    name: signal_manager_network
    driver: bridge
