# Generated by Django 2.0.1 on 2019-07-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('pipLocation', models.IntegerField()),
                ('displayPrecision', models.IntegerField()),
                ('minimumTradeSize', models.FloatField()),
                ('pipfactor', models.FloatField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
