# Generated by Django 2.0.1 on 2019-07-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='pipfactor',
            new_name='pipFactor',
        ),
        migrations.AddField(
            model_name='instrument',
            name='symbol',
            field=models.CharField(default=1, max_length=20, unique=False),
            preserve_default=False,
        ),
    ]
