# Generated by Django 2.0.1 on 2019-07-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0003_auto_20190716_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='symbol',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
