# Generated by Django 2.2.6 on 2020-02-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oanda', '0004_auto_20190716_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='asks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='bids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='closeoutAsk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='closeoutBid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='tick_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
