# Generated by Django 2.0.1 on 2019-07-17 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0004_auto_20190623_0857'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account_no', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('environment', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('risk', models.IntegerField(default=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Account')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.Channel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('stoploss', models.BooleanField(default=True)),
                ('manage_trade', models.BooleanField(default=False)),
                ('break_even', models.IntegerField(blank=True)),
                ('close_half', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.TextField()),
                ('order_symbol', models.TextField()),
                ('order_type', models.CharField(max_length=10)),
                ('order_stoploss', models.TextField()),
                ('order_price', models.TextField()),
                ('order_lot', models.TextField()),
                ('order_takeprofit', models.TextField()),
                ('order_status', models.CharField(choices=[('Cancled', 'Cancled'), ('Pending', 'Pending'), ('Closed', 'Closed'), ('Active', 'Active'), ('Deleted', 'Deleted')], default='', max_length=10)),
                ('open_price', models.TextField(blank=True)),
                ('open_time', models.DateTimeField(blank=True)),
                ('close_price', models.TextField(blank=True)),
                ('close_time', models.DateTimeField(blank=True)),
                ('message_id', models.TextField(default='0')),
                ('order_comment', models.CharField(blank=True, default='', max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Account')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.Signal')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='follower',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Strategy'),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Broker'),
        ),
        migrations.AddField(
            model_name='account',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Broker'),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.AccountType'),
        ),
        migrations.AlterUniqueTogether(
            name='trade',
            unique_together={('owner', 'account', 'order_id')},
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('owner', 'account', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='accounttype',
            unique_together={('broker', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('broker', 'owner', 'account_no')},
        ),
    ]
