# Generated by Django 2.0.1 on 2019-07-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='open_time',
        ),
    ]
