# Generated by Django 2.0.1 on 2019-07-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_auto_20190717_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='close_price',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='open_price',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='open_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
