# Generated by Django 2.0.1 on 2019-07-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_auto_20190717_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='order_lot',
            new_name='order_units',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='message_id',
        ),
        migrations.AddField(
            model_name='trade',
            name='error_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='error_reason',
            field=models.TextField(blank=True),
        ),
    ]
