# Generated by Django 2.0.1 on 2019-07-21 22:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0004_auto_20190718_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='order_id',
            new_name='orderid',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='order_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='order_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='order_stoploss',
            new_name='stoploss',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='order_symbol',
            new_name='symbol',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='order_takeprofit',
            new_name='takeprofit',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='order_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='order_units',
            new_name='units',
        ),
        migrations.AlterUniqueTogether(
            name='trade',
            unique_together={('owner', 'account', 'orderid')},
        ),
    ]
