# Generated by Django 2.0.1 on 2019-07-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_auto_20190721_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.TextField(choices=[(2, 'Cancled'), (0, 'Pending'), (5, 'Closed'), (1, 'Active'), (4, 'Deleted')], default='', max_length=10),
        ),
    ]
