# Generated by Django 2.0.1 on 2019-09-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_auto_20190731_1020'),
    ]


    operations = [
        migrations.AddField(
            model_name='trade',
            name='realizedPL',
            field=models.TextField(blank=True),
        ),
    ]
