# Generated by Django 2.0.1 on 2019-09-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_auto_20190923_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='close_reason',
            field=models.TextField(blank=True),
        ),
    ]
