# Generated by Django 2.0.1 on 2019-09-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0010_trade_close_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='pending_order',
            field=models.IntegerField(default=True),
        ),
    ]
