# Generated by Django 2.0.1 on 2019-09-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0011_strategy_pending_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='pending_order',
            field=models.BooleanField(default=True),
        ),
    ]
