# Generated by Django 2.2.6 on 2019-10-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0012_auto_20190926_1259'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trade',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, orderid='0'), name='orderidne0'),
        ),
    ]
