# Generated by Django 2.2.6 on 2019-11-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0013_auto_20191001_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='size_multiplier',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='strategy',
            name='size_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Stoploss'), (1, 'Risk'), (2, 'Fix'), (3, 'Multiplier')], default=0),
        ),
    ]
