# Generated by Django 2.2.6 on 2019-11-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0014_auto_20191105_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='size_multiplier',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
