# Generated by Django 2.2.6 on 2019-11-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0015_auto_20191105_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='units',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
