# Generated by Django 2.2.6 on 2019-11-13 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0016_strategy_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='linked_cnt',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='linked_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='linked_uid',
            field=models.CharField(blank=True, default='0', max_length=1, null=True),
        ),
#        migrations.AlterUniqueTogether(
#            name='trade',
#            unique_together={('owner', 'account', 'orderid', 'linked_uid')},
#        ),
    ]
