# Generated by Django 2.2.6 on 2019-12-11 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0017_auto_20191113_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='filter_direction',
            field=models.IntegerField(blank=True, choices=[(0, 'All'), (2, 'Long'), (1, 'Short')], default=0),
        ),
        migrations.AddField(
            model_name='strategy',
            name='filter_ea_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='filter_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategy',
            name='filter_lot_size',
            field=models.TextField(blank=True),
        ),
#        migrations.AlterUniqueTogether(
#            name='trade',
#            unique_together={('owner', 'account', 'orderid', 'linked_uid')},
#        ),
    ]
