# Generated by Django 2.2.6 on 2019-12-11 08:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0018_auto_20191211_0810'),
    ]
