# Generated by Django 2.2.6 on 2019-12-11 12:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0019_auto_20191211_0817'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trade',
            unique_together={('owner', 'account', 'orderid')},
        ),
        migrations.RemoveField(
            model_name='trade',
            name='linked_cnt',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='linked_id',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='linked_uid',
        ),
    ]
