# Generated by Django 2.2.6 on 2019-12-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0020_auto_20191211_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
