# Generated by Django 2.2.6 on 2020-04-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0022_auto_20191212_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='needsl',
            field=models.BooleanField(default=False),
        ),
    ]
