# Generated by Django 2.2.6 on 2020-04-07 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0023_strategy_needsl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='needsl',
        ),
    ]
