# Generated by Django 2.2.6 on 2020-04-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0024_remove_strategy_needsl'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='needsl',
            field=models.BooleanField(default=True),
        ),
    ]
