# Generated by Django 2.0.1 on 2019-06-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190615_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='signal_provider',
            field=models.BooleanField(default=False),
        ),
    ]
