# Generated by Django 2.0.1 on 2019-06-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_auto_20190619_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='type',
            field=models.CharField(choices=[(1, 'Free'), (2, 'Paid')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='signal',
            name='channel_type_free',
            field=models.CharField(choices=[(1, 'Free'), (2, 'Paid')], default='FREE', max_length=10),
        ),
        migrations.AddField(
            model_name='signal',
            name='channel_type_paid',
            field=models.CharField(choices=[(1, 'Free'), (2, 'Paid')], default='', max_length=10),
        ),
    ]
