# Generated by Django 2.0.1 on 2019-06-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_auto_20190621_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='type',
            field=models.CharField(choices=[(0, 'Free'), (1, 'Paid')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='signal',
            name='channel_type_free',
            field=models.CharField(choices=[(0, 'Free'), (1, 'Paid')], default='FREE', max_length=10),
        ),
        migrations.AlterField(
            model_name='signal',
            name='channel_type_paid',
            field=models.CharField(choices=[(0, 'Free'), (1, 'Paid')], default='', max_length=10),
        ),
    ]
