# Generated by Django 2.0.1 on 2019-09-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0004_auto_20190623_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='order_close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='order_create_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='order_open_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
