# Generated by Django 2.0.1 on 2019-09-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0005_auto_20190924_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='order_close_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='order_create_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='order_open_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
