# Generated by Django 2.2.6 on 2020-01-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0007_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
