# Generated by Django 2.2.6 on 2020-01-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0008_auto_20200110_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='channel_id',
            field=models.TextField(default='0'),
        ),
    ]
