# Generated by Django 2.2.6 on 2020-02-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0009_signal_channel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='channel_id',
        ),
    ]
