# Generated by Django 2.2.6 on 2020-04-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0010_remove_signal_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='order_stoploss',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signal',
            name='order_takeprofit',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
