# Generated by Django 2.2.6 on 2020-04-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0011_auto_20200403_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='order_close_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
